package com.keyou.fdcda.api.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class SysResource implements Serializable {
    static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RESOURCE.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RESOURCE.PARENT_ID
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RESOURCE.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RESOURCE.URL
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RESOURCE.TYPE
     *
     * @mbg.generated
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RESOURCE.SORT
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RESOURCE.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RESOURCE.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_RESOURCE.MODIFY_TIME
     *
     * @mbg.generated
     */
    private Date modifyTime;
    
    private List<SysResource> subResource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RESOURCE.ID
     *
     * @return the value of SYS_RESOURCE.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RESOURCE.ID
     *
     * @param id the value for SYS_RESOURCE.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RESOURCE.PARENT_ID
     *
     * @return the value of SYS_RESOURCE.PARENT_ID
     *
     * @mbg.generated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RESOURCE.PARENT_ID
     *
     * @param parentId the value for SYS_RESOURCE.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RESOURCE.NAME
     *
     * @return the value of SYS_RESOURCE.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RESOURCE.NAME
     *
     * @param name the value for SYS_RESOURCE.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RESOURCE.URL
     *
     * @return the value of SYS_RESOURCE.URL
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RESOURCE.URL
     *
     * @param url the value for SYS_RESOURCE.URL
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RESOURCE.TYPE
     *
     * @return the value of SYS_RESOURCE.TYPE
     *
     * @mbg.generated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RESOURCE.TYPE
     *
     * @param type the value for SYS_RESOURCE.TYPE
     *
     * @mbg.generated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RESOURCE.SORT
     *
     * @return the value of SYS_RESOURCE.SORT
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RESOURCE.SORT
     *
     * @param sort the value for SYS_RESOURCE.SORT
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RESOURCE.MEMO
     *
     * @return the value of SYS_RESOURCE.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RESOURCE.MEMO
     *
     * @param memo the value for SYS_RESOURCE.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RESOURCE.CREATE_TIME
     *
     * @return the value of SYS_RESOURCE.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RESOURCE.CREATE_TIME
     *
     * @param createTime the value for SYS_RESOURCE.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_RESOURCE.MODIFY_TIME
     *
     * @return the value of SYS_RESOURCE.MODIFY_TIME
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_RESOURCE.MODIFY_TIME
     *
     * @param modifyTime the value for SYS_RESOURCE.MODIFY_TIME
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public List<SysResource> getSubResource() {
        return subResource;
    }

    public void setSubResource(List<SysResource> subResource) {
        this.subResource = subResource;
    }
}