package com.keyou.fdcda.api.model;

import java.io.Serializable;
import java.util.Date;

public class SysRoleinfo implements Serializable {
    static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEINFO.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEINFO.ROLE_ID
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEINFO.RESOURCE_ID
     *
     * @mbg.generated
     */
    private Long resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEINFO.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEINFO.MODIFY_TIME
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEINFO.ID
     *
     * @return the value of SYS_ROLEINFO.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEINFO.ID
     *
     * @param id the value for SYS_ROLEINFO.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEINFO.ROLE_ID
     *
     * @return the value of SYS_ROLEINFO.ROLE_ID
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEINFO.ROLE_ID
     *
     * @param roleId the value for SYS_ROLEINFO.ROLE_ID
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEINFO.RESOURCE_ID
     *
     * @return the value of SYS_ROLEINFO.RESOURCE_ID
     *
     * @mbg.generated
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEINFO.RESOURCE_ID
     *
     * @param resourceId the value for SYS_ROLEINFO.RESOURCE_ID
     *
     * @mbg.generated
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEINFO.CREATE_TIME
     *
     * @return the value of SYS_ROLEINFO.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEINFO.CREATE_TIME
     *
     * @param createTime the value for SYS_ROLEINFO.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEINFO.MODIFY_TIME
     *
     * @return the value of SYS_ROLEINFO.MODIFY_TIME
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEINFO.MODIFY_TIME
     *
     * @param modifyTime the value for SYS_ROLEINFO.MODIFY_TIME
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}