package com.keyou.fdcda.app.dao.base;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

/**
 * Created by zzq on 2017-08-26.
 */
public interface BaseMapper<T, K extends Serializable> {
//    T findById(K id);

    List<T> findPage(Map<String, Object> map);

    K findPageCount(Map<String, Object> map);

    List<T> findAllPage(Map<String, Object> map);
//    
//    Integer update(T entity);
//    
//    void deleteById(K id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RESOURCE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(K id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RESOURCE
     *
     * @mbg.generated
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RESOURCE
     *
     * @mbg.generated
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RESOURCE
     *
     * @mbg.generated
     */
    T selectByPrimaryKey(K id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RESOURCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_RESOURCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(T record);
}
