package com.keyou.fdcda.app.dao;

import com.keyou.fdcda.api.model.SysUserrole;
import com.keyou.fdcda.app.dao.base.BaseMapper;

public interface SysUserroleMapper extends BaseMapper<SysUserrole, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERROLE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERROLE
     *
     * @mbg.generated
     */
    int insert(SysUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERROLE
     *
     * @mbg.generated
     */
    int insertSelective(SysUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERROLE
     *
     * @mbg.generated
     */
    SysUserrole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERROLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERROLE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUserrole record);
}